# Generates icons.js: a few inline SVG icons (Material Design Icons + Telegram logo from Font Awesome) plus emoji for the rest of the UI and trophies (src/icons/emoji.js). Nothing is loaded from third-party hosts.
import re, json, os, sys
# Run from repo root: python3 src/icons/make_icons.py [path to .icons]
# Icons come from the mkdocs-material package (pip download mkdocs-material, unpack wheel): material/templates/.icons
ROOT=sys.argv[1] if len(sys.argv)>1 else '/usr/local/lib/python3.11/dist-packages/material/templates/.icons'
SRC=os.path.join(os.path.dirname(os.path.abspath(__file__)),'..')
# SVG only where no emoji fits or for brand logos; everything else (incl. trophy badges) uses EMOJI
UI=['home-outline','chevron-right','google','weather-night','white-balance-sunny']
def load(path):
    t=open(path).read();vb=re.search(r'viewBox="([^"]+)"',t).group(1);ds=re.findall(r'<path[^>]*\sd="([^"]+)"',t)
    assert len(ds)==1,(path,len(ds));return [vb,ds[0]]+([1] if 'evenodd' in t else [])   # 3rd element: fill-rule evenodd
ICO={}
for n in sorted(UI):ICO[n]=load(f'{ROOT}/material/{n}.svg')
ICO['telegram']=load(f'{ROOT}/fontawesome/brands/telegram.svg')
# every trophy id must have an emoji (field i in trophies.js)
_t=open(os.path.join(SRC,'trophies.js')).read()
miss=[i for i,b in re.findall(r'\{id:"([a-z0-9]+)"([^}]*)',_t) if 'i:"' not in b];assert not miss,miss
EMOJI_JS=open(os.path.join(os.path.dirname(os.path.abspath(__file__)),'emoji.js')).read()
js=f'''// GENERATED by icons/make_icons.py, do not edit by hand.
// Icons: Material Design Icons (Pictogrammers, Apache-2.0) and Telegram logo from Font Awesome Free (CC BY 4.0).
const ICO={json.dumps(ICO,separators=(',',':'))};
function icon(n){{const x=ICO[n];return x?`<svg class="ico" viewBox="${{x[0]}}" aria-hidden="true"><path d="${{x[1]}}"${{x[2]?' fill-rule="evenodd"':''}}/></svg>`:EMOJI[n]?`<span class="ico em" aria-hidden="true">${{EMOJI[n]}}</span>`:'';}}   // no SVG: fall back to emoji
'''+EMOJI_JS
open(os.path.join(SRC,'icons.js'),'w').write(js)
print(len(ICO),'icons',len(js),'bytes')
