# Generates icons.js: inline SVG icons for the whole UI (Material Design Icons outline + Telegram logo from Font Awesome) plus emoji helpers for rewards (src/icons/emoji.js). Nothing is loaded from third-party hosts.
import re, json, os, sys
# Run from repo root: python3 src/icons/make_icons.py [path to .icons]
# Icons come from the mkdocs-material package (pip download mkdocs-material, unpack wheel): material/templates/.icons
ROOT=sys.argv[1] if len(sys.argv)>1 else '/usr/local/lib/python3.11/dist-packages/material/templates/.icons'
SRC=os.path.join(os.path.dirname(os.path.abspath(__file__)),'..')
# icon key used in code -> MDI glyph file (outline variants where they exist); emoji stay only for rewards (emoji.js)
UI={'home-outline':'home-outline','chevron-right':'chevron-right','google':'google','weather-night':'weather-night','white-balance-sunny':'white-balance-sunny',
'fire':'fire','sword-cross':'sword-cross','calendar-star':'calendar-star-outline','ferris-wheel':'ferris-wheel','soccer-field':'soccer-field','format-list-numbered':'format-list-numbered',
'share-variant':'export-variant','account-circle':'account-circle-outline','lock-open-variant':'lock-open-variant-outline','eye':'eye-outline','eye-off':'eye-off-outline',
'check-circle':'check-circle-outline','check-decagram':'check-decagram-outline','handshake':'handshake-outline','content-copy':'content-copy','star':'star-outline','account-group':'account-group-outline',
'format-quote-open':'format-quote-open-outline','pencil':'pencil-outline','logout':'logout','alert-outline':'alert-outline','calendar-check':'calendar-check-outline',
'account-multiple-check':'account-multiple-check-outline','bookshelf':'bookshelf','timer-sand':'timer-sand','restart':'restart','arrow-left-right':'arrow-left-right','swap-horizontal':'swap-horizontal',
'soccer':'soccer','shield-star':'shield-star-outline','heart':'heart-outline','lightning-bolt':'lightning-bolt-outline','arrow-down-bold':'arrow-down','trophy':'trophy-outline','crown':'crown-outline',
'mail':'email-outline','tv':'monitor-eye','close':'close'}
def load(path):
    t=open(path).read();vb=re.search(r'viewBox="([^"]+)"',t).group(1);ds=re.findall(r'<path[^>]*\sd="([^"]+)"',t)
    assert len(ds)==1,(path,len(ds));return [vb,ds[0]]+([1] if 'evenodd' in t else [])   # 3rd element: fill-rule evenodd
ICO={}
for n in sorted(UI):ICO[n]=load(f'{ROOT}/material/{UI[n]}.svg')
ICO['telegram']=load(f'{ROOT}/fontawesome/brands/telegram.svg')
# every trophy id must have an emoji (field i in trophies.js)
_t=open(os.path.join(SRC,'trophies.js')).read()
miss=[i for i,b in re.findall(r'\{id:"([a-z0-9]+)"([^}]*)',_t) if 'i:"' not in b];assert not miss,miss
EMOJI_JS=open(os.path.join(os.path.dirname(os.path.abspath(__file__)),'emoji.js')).read()
js=f'''// GENERATED by icons/make_icons.py, do not edit by hand.
// Icons: Material Design Icons (Pictogrammers, Apache-2.0) and Telegram logo from Font Awesome Free (CC BY 4.0).
const ICO={json.dumps(ICO,separators=(',',':'))};
function icon(n){{const x=ICO[n];return x?`<svg class="ico" viewBox="${{x[0]}}" aria-hidden="true"><path d="${{x[1]}}"${{x[2]?' fill-rule="evenodd"':''}}/></svg>`:'';}}
'''+EMOJI_JS
open(os.path.join(SRC,'icons.js'),'w').write(js)
print(len(ICO),'icons',len(js),'bytes')
